name: Run tests

on:
  push:
  workflow_dispatch:

  # schedule:
  #   - cron: "0 0 * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - run: bun install

      - run: bun run test
        env:
          OPENMAGICLINE_GYM: ${{ secrets.OPENMAGICLINE_GYM }}
          OPENMAGICLINE_USERNAME: ${{ secrets.OPENMAGICLINE_USERNAME }}
          OPENMAGICLINE_PASSWORD: ${{ secrets.OPENMAGICLINE_PASSWORD }}
          OPENMAGICLINE_TEST_CUSTOMER: ${{ secrets.OPENMAGICLINE_TEST_CUSTOMER }}
          OPENMAGICLINE_TEST_FACILITY: ${{ secrets.OPENMAGICLINE_TEST_FACILITY }}
