name: Run tests

on:
  push:
  workflow_dispatch:

  # schedule:
  #   - cron: "0 0 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    concurrency:
      group: omgl-test
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - run: bun install

      - uses: nick-fields/retry@v3
        with:
          timeout_minutes: 15
          max_attempts: 3
          retry_on: error
          command: bun run test
        env:
          OPENMAGICLINE_GYM: ${{ secrets.OPENMAGICLINE_GYM }}
          OPENMAGICLINE_USERNAME: ${{ secrets.OPENMAGICLINE_USERNAME }}
          OPENMAGICLINE_PASSWORD: ${{ secrets.OPENMAGICLINE_PASSWORD }}
          OPENMAGICLINE_TEST_CUSTOMER: ${{ secrets.OPENMAGICLINE_TEST_CUSTOMER }}
          OPENMAGICLINE_TEST_FACILITY: ${{ secrets.OPENMAGICLINE_TEST_FACILITY }}
